name: 'Telnyx PR Reviewer'
description: 'A GitHub Action to review pull requests using Telnyx AI'
branding:
  icon: 'check-circle'
  color: 'green'
author: 'team-telnyx'
inputs:
  telnyx_api_key:
    description: 'Telnyx API Key'
    required: true
  model_name:
    description: 'Model Name'
    default: 'meta-llama/Meta-Llama-3.1-8B-Instruct'
  custom_message:
    description: 'Custom message for the AI review prompt'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Review PR
      shell: bash
      run: |
        echo "Reviewing PR in $GITHUB_REPOSITORY"

        # Get the diff of the current branch against the base branch
        pr_diff=$(gh pr diff ${{ github.event.number }} --patch | grep -vE "^$" | jq -Rsa . | sed -E 's/(^.)|(.$)//g')

        # Use custom message if provided, otherwise use the default message
        if [ -n "$CUSTOM_MESSAGE" ]; then
          review_message=$(echo "$CUSTOM_MESSAGE" | grep -vE "^$" | jq -Rsa . | sed -E 's/(^.)|(.$)//g')
        else
          review_message="Review this PR for me, be descriptive but straightforward, tell me what it does, a brief summary of the changes and if there are any reasons to reject this PR:"
        fi

        echo "Building payload"
        json_payload=$(cat <<EOF
        {
          "model": "$MODEL_NAME",
          "messages": [{"role": "user", "content": "$review_message\n$pr_diff"}]
        }
        EOF
        )

        # Query TelnyxInference and extract only the response content
        response=$(curl -s https://api.telnyx.com/v2/ai/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TELNYX_API_KEY" \
          -d "$json_payload" | jq -r ".choices[].message.content")

        if [ $? -ne '0' ]; then
          echo "Unable to contact TelnyxInference"
          echo "Exiting with status 0 so we don't block merges and this is probably caused by a large diff"
          exit 0
        fi

        # Publish the review comment using gh CLI
        set +e
        gh pr comment ${{ github.event.number }} -b "Automated $MODEL_NAME review: $response" --edit-last

        if [ $? -ne '0' ]; then
          gh pr comment ${{ github.event.number }} -b "Automated $MODEL_NAME review: $response"
        fi
        set -e
      env:
        TELNYX_API_KEY: ${{ inputs.telnyx_api_key }}
        MODEL_NAME: ${{ inputs.model_name }}
        CUSTOM_MESSAGE: ${{ inputs.custom_message }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
